### PR TITLE
[Add] `itemset` function to fill in a scalar at the certain coordinates of a ndarray

### PR DESCRIPTION
**Pull request by forFudan**
Add `itemset` function to fill in a scalar at the certain coordinates of a ndarray.

It is similar to `numpy.ndarray.itemset`. It is better then `__setitem__`.

Now we have both `item` and `itemset` function to read and write a scalar into the array.

```mojo
import numojo as nm

fn main() raises:
    var A = nm.zeros[nm.i16](3, 3)
    print(A)
    A.itemset(5, 256)
    print(A)
    A.itemset(List(1,1), 1024)
    print(A)
```

### CODE REVIEW

**Comment by MadAlex1997** [comment]
Considering that `itemset` got removed from numpy in 2.0 do we still want to have it or if we do should we name it that?

**Comment by shivasankarka** [comment]
I think we should keep these features for now given the possibility that Mojo might not resolve the symmetric getter and setter problem anytime soon. In such case, having the `item` and `itemset` temporarily will be a good option. We can deprecate it later if needed.

**Comment by MadAlex1997** [comment]
Either we need to pin the numpy to <2.0 or we need to rewrite the numpy part of the test to use `array[index]=value`.

**Comment by forFudan** [comment]
Yes. I will rewrite the file using A[0] = 1.

**Comment by forFudan** [comment]
Talk about this. We can maybe use the following way for setitem and getitem to indicate that we want a scalar instead of a ndarray. Namely, enclose the coordinates in a tuple or list.

`A[(0)]`
`A[(0, 1)]`

**Comment by forFudan** [comment]
> Talk about this. We can maybe use the following way for setitem and getitem to indicate that we want a scalar instead of a ndarray. Namely, enclose the coordinates in a tuple (we now already have list as input).
> 
> `A[(0)]` `A[(0, 1)]`

Okay, it is not possible now because the Tuple type is not yet iterable.

**Review by MadAlex1997 — APPROVED** [review]

**Comment by shivasankarka** [comment]
@forFudan @MadAlex1997 What's your opinion of doing something like the following instead of `item`, `itemset`.

```py
struct item():
    ...
      
var A = NDArray[i32](10, 10)
print(A[item(5,2)])  #__getitem__(self, idx: item)
A[item(5,2)] = 10.0 #__setitem__(self, idx: item)
```

This is almost same as `item` and `itemset`, but it will be more close to the Tuple syntax. We can easily switch it out with `Tuple` in future when `Tuple` is utterable. I think the transition will be easier.

**Pull request merged**
